-- MySQL Script generated by MySQL Workbench
-- qui 21 mar 2024 20:34:52
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`mae`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`mae` (
  `id_mae` INT NOT NULL AUTO_INCREMENT,
  `nome_mae` VARCHAR(100) NOT NULL,
  `telefone` VARCHAR(45) NULL,
  `endereco` VARCHAR(45) NULL,
  `data_nasc` DATE NULL,
  PRIMARY KEY (`id_mae`),
  UNIQUE INDEX `id_aluno_UNIQUE` (`id_mae` ASC) VISIBLE,
  UNIQUE INDEX `cpf_aluno_UNIQUE` (`nome_mae` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`bebe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`bebe` (
  `id_bebe` INT NOT NULL,
  `data_nasc` VARCHAR(45) NOT NULL,
  `peso` DOUBLE NOT NULL,
  `altura` DOUBLE NOT NULL,
  `mae_id_mae` INT NOT NULL,
  PRIMARY KEY (`id_bebe`, `mae_id_mae`),
  INDEX `fk_bebe_mae_idx` (`mae_id_mae` ASC) VISIBLE,
  CONSTRAINT `fk_bebe_mae`
    FOREIGN KEY (`mae_id_mae`)
    REFERENCES `mydb`.`mae` (`id_mae`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`medico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`medico` (
  `nome_medico` VARCHAR(45) NOT NULL,
  `telefone_med` VARCHAR(45) NOT NULL,
  `CRM_medico` VARCHAR(45) NOT NULL,
  `especialidade` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`CRM_medico`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`medico_has_bebe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`medico_has_bebe` (
  `medico_CRM_medico` VARCHAR(45) NOT NULL,
  `bebe_id_bebe` INT NOT NULL,
  `bebe_mae_id_mae` INT NOT NULL,
  PRIMARY KEY (`medico_CRM_medico`, `bebe_id_bebe`, `bebe_mae_id_mae`),
  INDEX `fk_medico_has_bebe_bebe1_idx` (`bebe_id_bebe` ASC, `bebe_mae_id_mae` ASC) VISIBLE,
  INDEX `fk_medico_has_bebe_medico1_idx` (`medico_CRM_medico` ASC) VISIBLE,
  CONSTRAINT `fk_medico_has_bebe_medico1`
    FOREIGN KEY (`medico_CRM_medico`)
    REFERENCES `mydb`.`medico` (`CRM_medico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_medico_has_bebe_bebe1`
    FOREIGN KEY (`bebe_id_bebe` , `bebe_mae_id_mae`)
    REFERENCES `mydb`.`bebe` (`id_bebe` , `mae_id_mae`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
