-- MySQL Script generated by MySQL Workbench
-- qui 21 mar 2024 20:22:48
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cliente` (
  `id_cliente` INT NOT NULL,
  PRIMARY KEY (`id_cliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`apolice`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`apolice` (
  `id_apolice` INT NOT NULL,
  PRIMARY KEY (`id_apolice`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`carro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`carro` (
  `id_carro` INT NOT NULL,
  `cliente_id_cliente` INT NOT NULL,
  `apolice_id_apolice` INT NOT NULL,
  PRIMARY KEY (`id_carro`, `cliente_id_cliente`),
  INDEX `fk_carro_cliente_idx` (`cliente_id_cliente` ASC) VISIBLE,
  INDEX `fk_carro_apolice1_idx` (`apolice_id_apolice` ASC) VISIBLE,
  CONSTRAINT `fk_carro_cliente`
    FOREIGN KEY (`cliente_id_cliente`)
    REFERENCES `mydb`.`cliente` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_carro_apolice1`
    FOREIGN KEY (`apolice_id_apolice`)
    REFERENCES `mydb`.`apolice` (`id_apolice`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`acidente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`acidente` (
  `id_acidente` INT NOT NULL,
  `carro_id_carro` INT NOT NULL,
  `carro_cliente_id_cliente` INT NOT NULL,
  PRIMARY KEY (`id_acidente`),
  INDEX `fk_acidente_carro1_idx` (`carro_id_carro` ASC, `carro_cliente_id_cliente` ASC) VISIBLE,
  CONSTRAINT `fk_acidente_carro1`
    FOREIGN KEY (`carro_id_carro` , `carro_cliente_id_cliente`)
    REFERENCES `mydb`.`carro` (`id_carro` , `cliente_id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pagamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pagamento` (
  `id_pagamento` INT NOT NULL,
  `data_vencimento` DATE NULL,
  `data_pagamento` DATE NULL,
  `apolice_id_apolice` INT NOT NULL,
  PRIMARY KEY (`id_pagamento`, `apolice_id_apolice`),
  INDEX `fk_pagamento_apolice1_idx` (`apolice_id_apolice` ASC) VISIBLE,
  CONSTRAINT `fk_pagamento_apolice1`
    FOREIGN KEY (`apolice_id_apolice`)
    REFERENCES `mydb`.`apolice` (`id_apolice`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
